#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/jetxceldesk/jetxceldesk /usr/bin/jetxceldesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/jetxceldesk.service ]; then
			rm /etc/systemd/system/jetxceldesk.service /usr/lib/systemd/system/jetxceldesk.service /usr/lib/systemd/user/jetxceldesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/jetxceldesk/files/systemd/jetxceldesk.service /usr/lib/systemd/system/jetxceldesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload jetxceldesk.service: Unit jetxceldesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/jetxceldesk.service:10: Executable path is not absolute: pkill -f "jetxceldesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/jetxceldesk.service
		fi
		systemctl daemon-reload
		systemctl enable jetxceldesk
		systemctl start jetxceldesk
	fi
fi
